### ISSUE TITLE
weight_initialization_exercise.ipynb exception in cell

### ISSUE THREAD

**Issue by dgloukhman** [udacity/deep-learning-v2-pytorch#252] opened 2020-04-27 09:49 UTC
the cell with the following code
`helpers.hist_dist('Random Uniform (low=-3, high=3)', np.random.uniform(-3, 3, [1000]))`

triggers following exception:

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/numpy/core/function_base.py in linspace(start, stop, num, endpoint, retstep, dtype, axis)
    116     try:
--> 117         num = operator.index(num)
    118     except TypeError:

TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-8-34327320d544> in <module>
----> 1 helpers.hist_dist('Random Uniform (low=-3, high=3)', np.random.uniform(-3, 3, [1000]))

~/Desktop/deep-learning-v2-pytorch/weight-initialization/helpers.py in hist_dist(title, distribution_tensor, hist_range)
    106     """
    107     plt.title(title)
--> 108     plt.hist(distribution_tensor, np.linspace(*hist_range, num=len(distribution_tensor)/2))
    109     plt.show()

<__array_function__ internals> in linspace(*args, **kwargs)

~/opt/anaconda3/envs/udacity/lib/python3.8/site-packages/numpy/core/function_base.py in linspace(start, stop, num, endpoint, retstep, dtype, axis)
    117         num = operator.index(num)
    118     except TypeError:
--> 119         raise TypeError(
    120             "object of type {} cannot be safely interpreted as an integer."
    121                 .format(type(num)))

TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.`

**Comment by rogalskim** [comment] 2020-05-15 12:42
I've just run into the same problem and decided to take a closer look. It turned out that it is caused by how the behavior of the division operator changed between Python 2 and 3.

The fix for this is very simple: replace "normal" division operator with integer division ("//").

Made a pull request with that fix here: #261

**Comment by abhiojha8** [comment] 2021-03-30 14:19
This is resolved with PR #261

**Closed by abhiojha8** 2021-03-30 14:19 UTC
