### ISSUE TITLE
images Tensor needs to be moved to CPU (cifar10_cnn_exercise.ipynb)

### ISSUE THREAD

**Issue by bfeeny** [udacity/deep-learning-v2-pytorch#270] opened 2020-06-12 05:27 UTC
[This](https://github.com/udacity/deep-learning-v2-pytorch/blob/master/convolutional-neural-networks/cifar-cnn/cifar10_cnn_exercise.ipynb) has an error in the last part of the notebook **Visualize Sample Test Results**

If student has `images` Tensor on the GPU, then `imshow(images[idx])` will fail with

`TypeError: can't convert non-cpu tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.`

The solution notebook has it correct, it should be changed to `imshow(images.cpu()[idx])`

**Comment by gargarchit** [comment] 2020-06-12 05:34
I just have a look and found that it is duplicate of #258
Also, a PR is already raised for this issue #226

**Closed** 2021-03-08 05:10 UTC
